### ISSUE TITLE
Update download documentation to include client creation

### ISSUE THREAD

**Issue by moutasemalakkad** [NVIDIA/NeMo-Curator#100]
**Describe the bug**

NeMo Curator is not functioning correctly in a Docker environment. The docker pull command for nvcr.io/nvidia/nemo:24.01.01.framework does not include NeMo Curator. After cloning the NeMo Curator repository and installing it, I encountered an issue where NeMo Curator failed to initialize Dask properly, resulting in runtime errors related to locks.

**Steps/Code to reproduce bug**

1. Pull the NVIDIA NGC Docker image:
   ```bash
   docker pull nvcr.io/nvidia/nemo:24.01.01.framework
   ```

2. Run the following code snippet:
   ```python
   from nemo_curator.download import download_wikipedia

   wikipedia = download_wikipedia("/workspace/nemo/wiki_download", dump_date="20240201", language="ar")
   # wikipedia.to_json('/workspace/nemo/wiki_download/downloads') 
   ```
**Work around**
1. Clone the NeMo Curator repository:
   ```bash
   git clone https://github.com/NVIDIA/NeMo-Curator
   ```
2. cd into Nemo-Curator
3. pip install .
4. Install NeMo Curator with CUDA support: (did not function with out this step)
   ```bash
   pip install .[cuda12x] --extra-index-url https://pypi.nvidia.com
   ```
**Expected behavior**

NeMo Curator should initialize Dask properly and allow the downloading and processing of Wikipedia dumps without runtime errors related to lock initialization.

**Environment overview**

- Environment location: Docker, LambdaCloud
- Method of NeMo-Curator install: workaround From source
  ```bash
  git clone https://github.com/NVIDIA/NeMo-Curator
  pip install .[cuda12x] --extra-index-url https://pypi.nvidia.com
  ```

**Environment details**

- OS version: Ubuntu 20.04
- Dask version: 2023.3.2
- Python version: 3.10

**Additional context**

- Docker pull command: `docker pull nvcr.io/nvidia/nemo:24.01.01.framework`
- Docker run command:
  ```bash
  docker run --gpus all -it --rm -v /home/ubuntu/arizona-storage:/workspace nvcr.io/nvidia/nemo:24.01.01.framework /bin/bash
  ```

During the execution of NeMo Curator, I encountered the following error related to Dask lock initialization:
```plaintext
Traceback (most recent call last):
  File "/workspace/wiki.py", line 4, in <module>
    wikipedia.to_json('/workspace/nemo/wiki_download/downloads')
  File "/usr/local/lib/python3.10/dist-packages/nemo_curator/datasets/doc_dataset.py", line 99, in to_json
    write_to_disk(
  File "/usr/local/lib/python3.10/dist-packages/nemo_curator/utils/distributed_utils.py", line 465, in write_to_disk
    df.to_json(
  File "/usr/local/lib/python3.10/dist-packages/dask/dataframe/core.py", line 1937, in to_json
    return to_json(self, filename, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/dask/dataframe/io/json.py", line 98, in to_json
    return list(dask_compute(*parts, **compute_kwargs))
  File "/usr/local/lib/python3.10/dist-packages/dask/base.py", line 628, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/dask/dataframe/io/io.py", line 842, in __call__
    return self.func(
  File "/usr/local/lib/python3.10/dist-packages/nemo_curator/download/doc_builder.py", line 123, in _download_and_extract_single_partition
    downloaded_file = downloader.download(url)
  File "/usr/local/lib/python3.10/dist-packages/nemo_curator/download/wikipedia.py", line 602, in download
    with self._lock:
  File "/usr/local/lib/python3.10/dist-packages/distributed/lock.py", line 174, in __enter__
    self.acquire()
  File "/usr/local/lib/python3.10/dist-packages/distributed/lock.py", line 142, in acquire
    self._verify_running()
  File "/usr/local/lib/python3.10/dist-packages/distributed/lock.py", line 113, in _verify_running
    raise RuntimeError(
RuntimeError: <class 'distributed.lock.Lock'> object not properly initialized. This can happen if the object is being deserialized outside of the context of a Client or Worker.
```

To resolve the issue temporarily, I had to manually initiate the Dask client. Like so:

import os
from nemo_curator.download import download_wikipedia
from dask.distributed import Client, LocalCluster
```
def main():
    # Set up Dask LocalCluster and Client
    cluster = LocalCluster()
    client = Client(cluster)

    output_path = "./curator_out_wiki"
    language = "ar"
    dump_date = "20240201"
    raw_download_dir = os.path.join(output_path, "downloads")

    # Ensure the output and download directories exist
    os.makedirs(output_path, exist_ok=True)
    os.makedirs(raw_download_dir, exist_ok=True)

    # Download Wikipedia dataset
    wikipedia = download_wikipedia(
        output_path=output_path,
        language=language,
        dump_date=dump_date,
        raw_download_dir=raw_download_dir,
        keep_raw_download=True,
        force_download=True  # Ensure it downloads even if files exist
    )
    # wikipedia.to_json('./out') #outputs .part unnecasry 

    print(f"Downloaded Wikipedia dataset: {wikipedia}")

    # Close the Dask client
    client.close()

if __name__ == "__main__":
    main()
```

**Comment by moutasemalakkad** [comment]
One more question, is it possible to run such processes on CPUs?

**Comment by ayushdg** [comment]
Thanks for raising @moutasemalakkad. Answering some of your questions inline:
> The docker pull command for nvcr.io/nvidia/nemo:24.01.01.framework does not include NeMo Curator

Yup, you're right this is an older container which doesn't include NeMo-Curator. I would recommend the [latest container](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/nemo/tags) `nvcr.io/nvidia/nemo:24.05` which does ship with NeMo-Curator pre-installed. 
Alternatively you can now also install via pypi using `pip install nemo-curator`.

> Install NeMo Curator with CUDA support: (did not function with out this step)

The download functionality of NeMo-Curator does not require GPUs and installing NeMo Curator without CUDA support should also work. Some features like Fuzzy deduplication require GPUs, other's like exact deduplication & dataClassification have GPU support for performance.

> During the execution of NeMo Curator, I encountered the following error related to Dask lock initialization, To resolve the issue temporarily, I had to manually initiate the Dask client.

Most features in NeMo-Curator require a Dask client to be initialized. NeMo-Curator also includes a `get_client` API to create a CPU or GPU based cluster based on the arguments provided. https://github.com/NVIDIA/NeMo-Curator/blob/4f851da8e00455c08569adf5cd7ac13a12b6cc61/nemo_curator/utils/distributed_utils.py#L95-L106

Also linking an [example](https://github.com/NVIDIA/NeMo-Curator/blob/4f851da8e00455c08569adf5cd7ac13a12b6cc61/examples/download_wikipedia.py#L31) which uses this.


Perhaps we can improve error messages when working with tasks that require a client to be initialized and throw a relevant message accordingly.

**Comment by moutasemalakkad** [comment]
Perfect, thanks for the clarification! I was following the following ReadMe and had the impression that I did not need to initialize the client. 

`https://github.com/NVIDIA/NeMo-Curator/blob/main/docs/user-guide/Download.rst`

**Comment by ayushdg** [comment]
Thanks for sharing the link. We should update the documentation to reflect that the client needs to be created!

**Comment by ryantwolf** [comment]
Closing as this has been updated.
