### ISSUE TITLE
Unnable to run exact_deduplication script

### ISSUE THREAD

**Issue by Manel-Hik** [NVIDIA/NeMo-Curator#19]
Hi 
I'm working on deduplicating s data of jsonl file
I'm following the documentation 
I generated ids with the add_id script
Then I'm running the exact_ deduplication script
But it throws tgis error
`Reading 5 files
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/dask/dataframe/utils.py", line 194, in raise_on_meta_error
    yield
  File "/opt/conda/lib/python3.10/site-packages/dask/dataframe/core.py", line 6895, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/opt/conda/lib/python3.10/site-packages/nemo_curator/utils/distributed_utils.py", line 220, in read_single_partition
    df = read_f(file, **read_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/json/_json.py", line 733, in read_json
    json_reader = JsonReader(
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/json/_json.py", line 818, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/json/_json.py", line 858, in _get_data_from_filepath
    self.handles = get_handle(
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
IsADirectoryError: [Errno 21] Is a directory: '/home/ubuntu/for_nlp_tasks/R_and_D/deduplication/nemo_dedup_samples/cc_samples_id_input/.ipynb_checkpoints'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/for_nlp_tasks/R_and_D/deduplication/nemo_dedup_samples/exact_deduplication.py", line 86, in <module>
    main(attach_args().parse_args())
  File "/home/ubuntu/for_nlp_tasks/R_and_D/deduplication/nemo_dedup_samples/exact_deduplication.py", line 43, in main
    input_dataset = DocumentDataset.read_json(dataset_dir, backend=backend)
  File "/opt/conda/lib/python3.10/site-packages/nemo_curator/datasets/doc_dataset.py", line 46, in read_json
    _read_json_or_parquet(
  File "/opt/conda/lib/python3.10/site-packages/nemo_curator/datasets/doc_dataset.py", line 201, in _read_json_or_parquet
    raw_data = read_data(
  File "/opt/conda/lib/python3.10/site-packages/nemo_curator/utils/distributed_utils.py", line 284, in read_data
    return dd.from_map(
  File "/opt/conda/lib/python3.10/site-packages/dask/dataframe/io/io.py", line 1028, in from_map
    meta = _emulate(
  File "/opt/conda/lib/python3.10/site-packages/dask/dataframe/core.py", line 6894, in _emulate
    with raise_on_meta_error(funcname(func), udf=udf), check_numeric_only_deprecation():
  File "/opt/conda/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/conda/lib/python3.10/site-packages/dask/dataframe/utils.py", line 215, in raise_on_meta_error
    raise ValueError(msg) from e
ValueError: Metadata inference failed in `read_single_partition`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
IsADirectoryError(21, 'Is a directory')

Traceback:
---------
  File "/opt/conda/lib/python3.10/site-packages/dask/dataframe/utils.py", line 194, in raise_on_meta_error
    yield
  File "/opt/conda/lib/python3.10/site-packages/dask/dataframe/core.py", line 6895, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/opt/conda/lib/python3.10/site-packages/nemo_curator/utils/distributed_utils.py", line 220, in read_single_partition
    df = read_f(file, **read_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/json/_json.py", line 733, in read_json
    json_reader = JsonReader(
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/json/_json.py", line 818, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/json/_json.py", line 858, in _get_data_from_filepath
    self.handles = get_handle(
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
`
I'm sure that my folder has the correct jsonl file with the new id created
like this 
` dataset_dir = "cc_samples_id_input"
    log_dir = "./"
    output_dir = "./"
    dataset_id_field = "adlr_id"
    dataset_text_field = "text"
`
Could you help me to figure it out please
thanks in advance

**Comment by ryantwolf** [comment]
Hello!

From the looks of it, you probably have started a jupyter notebook in that directory at some point. That created the directory `cc_samples_id_input/.ipynb_checkpoints`. The `DocumentDataset.read_json` method then tries to read that directory in as a file, and fails (since it's a directory). You can fix this by either deleting `.ipynb_checkpoints`, or moving your data to a different directory that does not have these jupyter checkpoints. Let me know if you have any more issues.

**Comment by Manel-Hik** [comment]
Hi 
It's weired I didn't started a jupyer notebook there, but I deleted that folder and run again it works
here is the output

Reading 4 files
Writing to disk complete for 4 partitions
14.255888938903809

It gaves parquet files
But I still need some help on how to understand the output
I printed the head of one parquet file, 
but how to know  the removed part of the text  which is repeated

**Comment by ryantwolf** [comment]
The [exact deduplication example](https://github.com/NVIDIA/NeMo-Curator/blob/main/examples/exact_deduplication.py) should walk you through how you can remove the duplicate documents after they are labelled. Of course, there are other ways you can remove them like if you'd prefer to keep more recent documents over older documents or some other metadata-based preference.
