### ISSUE TITLE
Unable to run distributed_data_classification tutorial

### ISSUE THREAD

**Issue by pappagari** [NVIDIA/NeMo-Curator#296]
**Describe the bug**
```

2024-10-11 00:49:45,532 - distributed.nanny - ERROR - Failed to start process
Traceback (most recent call last):
  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/distributed/nanny.py", line 452, in instantiate
    result = await self.process.start()
  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/distributed/nanny.py", line 749, in start
    await self.process.start()
  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/distributed/process.py", line 55, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/distributed/process.py", line 215, in _start
    process.start()
  File "/opt/conda/envs/nemo3/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/conda/envs/nemo3/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/opt/conda/envs/nemo3/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/conda/envs/nemo3/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/conda/envs/nemo3/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/opt/conda/envs/nemo3/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/opt/conda/envs/nemo3/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Steps/Code to reproduce bug**

I am trying to work on something similar to the tutorial at tutorial tutorials/distributed_data_classification/distributed_data_classification.ipynb

For this, I converted this notebook to python script using `jupyter nbconvert --to script` and replaced the following lines with `os.environ['DASK_DATAFRAME__QUERY_PLANNING'] = 'False'`

```
get_ipython().run_line_magic('env', 'PYTHONWARNINGS=ignore')
get_ipython().run_line_magic('env', 'DASK_DATAFRAME__QUERY_PLANNING=False')
```

I tried to debug by limiting to cpu and 1 worker through `client = get_client(cluster_type="cpu", n_workers=1)`. 
But, strangely, just after this line the execution goes back to the beginning of the file again. I continued the execution and the second time get_client is executed, I get the error pasted above.

**Environment overview (please complete the following information)**

I installed from the source as mentioned in the installation instructions. And here are some important package versions. 

OS version -- Ubuntu 22.04.5 LTS (GNU/Linux 6.8.0-1015-aws x86_64)
Python version -- 3.10.15
pip version -- 24.2

**Comment by ayushdg** [comment]
I believe this is similar to: https://stackoverflow.com/questions/60232708/dask-fails-with-freeze-support-bug.

When running in an interactive session like ipython/jupyter using the `get_client` api works directly. 

While running the same in a python script, you need to wrap methods like `get_client` which spawn new processes in a block like this one: 

```python
if __name__ == "__main__":
    get_client ...
```

More info on why this is needed is quoted in the python multiprocessing [guidelines](https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods).

Here's a classifier example that uses this same block that can be used for reference: https://github.com/NVIDIA/NeMo-Curator/blob/main/examples/classifiers/quality_example.py

**Comment by pappagari** [comment]
Thanks! I think that sorted out the error. However, I get the following error. I tried it in the terminal with jupyter console and it ran successfully with the df columns as "text" and "domain_pred". I think another change is required in the codebase to write the result to a json file.

```
args:      (['_prob'], 'rename-afc341d5dd2e8120ec617f9e1069e876', None, '<crossfit.op.label.Labeler object at 0x7e78014dce8-79aed2412ac84bf844bc20cd648113d8', {'number': 0, 'division': 0}, '<crossfit.backend.torch.op.base.Predictor object a-bd85e7dd87751d0b2a1341c8d8ce8ca4', '<crossfit.op.tokenize.Toke
nizer object at 0x7e7806-b0a7595186adc418a4ae53030bf38db2', 'assign-bd8164aa372cd7b7a960f4bb2b55ae67',                                                 text                                                                                                                                                    
0  Quantum computing is set to revolutionize the ...                                                                                                   
1  Investing in index funds is a popular strategy...                       
2  Recent advancements in gene therapy offer new ...                                                                                                   
3  Online learning platforms have transformed the...                                                                                                   
4  Traveling to Europe during the off-season can ...                                                                                                   
5  Training regimens for athletes have become mor...                                                                                                   
6  Streaming services are changing the way people...                                                                                                   
7  Vegan recipes have gained popularity as more p...                                                                                                   
8  Climate change research is critical for develo...                                                                                                   
9  Telemedicine has become increasingly popular d..., 'sliced_text', 'str',                                                                            
kwargs:    {}                                                              
Exception: 'TypeError("ListColumn.__init__() missing 1 required positional argument: \'data\'")'                                                       
Traceback: '  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/optimization.py", line 1028, in __call__\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/core.py", line 163, in get\n    result = _execu
te_task(task, cache)\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/core.py", line 133, in _execute_task\n    return func(*(_execute_task(a, cache) for a in args))\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/core.py", line 133, in <genexpr>\n    return func(*(_exe
cute_task(a, cache) for a in args))\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/core.py", line 127, in _execute_task\n    return [_execute_task(a, cache) for a in arg]\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/core.py", line 127, in <listcomp>\n    return [_e
xecute_task(a, cache) for a in arg]\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/core.py", line 133, in _execute_task\n    return func(*(_execute_task(a, cache) for a in args))\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/core.py", line 133, in <genexpr>\n    ret
urn func(*(_execute_task(a, cache) for a in args))\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/core.py", line 127, in _execute_task\n    return [_execute_task(a, cache) for a in arg]\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/core.py", line 127, in <listcomp>\
n    return [_execute_task(a, cache) for a in arg]\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/core.py", line 133, in _execute_task\n    return func(*(_execute_task(a, cache) for a in args))\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/core.py", line 133, in <ge
nexpr>\n    return func(*(_execute_task(a, cache) for a in args))\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/core.py", line 127, in _execute_task\n    return [_execute_task(a, cache) for a in arg]\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/core.py", line 127,
 in <listcomp>\n    return [_execute_task(a, cache) for a in arg]\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/core.py", line 133, in _execute_task\n    return func(*(_execute_task(a, cache) for a in args))\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/core.py", l
ine 133, in <genexpr>\n    return func(*(_execute_task(a, cache) for a in args))\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/core.py", line 127, in _execute_task\n    return [_execute_task(a, cache) for a in arg]\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/core
.py", line 127, in <listcomp>\n    return [_execute_task(a, cache) for a in arg]\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/core.py", line 133, in _execute_task\n    return func(*(_execute_task(a, cache) for a in args))\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/d
ask/utils.py", line 78, in apply\n    return func(*args, **kwargs)\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/dataframe/core.py", line 7175, in apply_and_enforce\n    df = func(*args, **kwargs)\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/dataframe/core.py", li
ne 7084, in func\n    return orig_func(*args, **kwargs, partition_info=partition_info)\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/crossfit/op/base.py", line 96, in __call__\n    output = self.call(data, *args, **kwargs)\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/crossf
it/op/tokenize.py", line 155, in call\n    input_ids, attention_mask = self.call_column(data[col])\n  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/crossfit/op/tokenize.py", line 129, in call_column\n    input_ids = create_list_series_from_1d_or_2d_ar(\n  File "/opt/conda/envs/nemo3/lib/pyth
on3.10/site-packages/crossfit/backend/cudf/series.py", line 35, in create_list_series_from_1d_or_2d_ar\n    lc = cudf.core.column.ListColumn(\n'       
                                                                                                                                                       
Traceback (most recent call last):                                                                                                                     
  File "/home/ubuntu/NeMo-Curator/tutorials/distributed_data_classification/distributed_data_classification.py", line 105, in <module>                 
    result_dataset.to_json(output_file_dir=output_file_path, write_to_filename=write_to_filename)                                                      
  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/nemo_curator/datasets/doc_dataset.py", line 103, in to_json                                                                                                                                                                                         
    write_to_disk(                                                         
  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/nemo_curator/utils/distributed_utils.py", line 522, in write_to_disk                        
    df.to_json(                                                                                                                                        
  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/dataframe/core.py", line 2072, in to_json                                              
    return to_json(self, filename, *args, **kwargs)                        
  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/dataframe/io/json.py", line 95, in to_json                                             
    return list(dask_compute(*parts, **compute_kwargs))
  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/dask/base.py", line 660, in compute                                                         
    results = schedule(dsk, keys, **kwargs)
  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/crossfit/op/base.py", line 96, in __call__                                                  
    output = self.call(data, *args, **kwargs)
  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/crossfit/op/tokenize.py", line 155, in call                                                 
    input_ids, attention_mask = self.call_column(data[col])
  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/crossfit/op/tokenize.py", line 129, in call_column                                          
    input_ids = create_list_series_from_1d_or_2d_ar(
  File "/opt/conda/envs/nemo3/lib/python3.10/site-packages/crossfit/backend/cudf/series.py", line 35, in create_list_series_from_1d_or_2d_ar           
    lc = cudf.core.column.ListColumn(
TypeError: ListColumn.__init__() missing 1 required positional argument: 'data' 
```

**Comment by ayushdg** [comment]
Thanks. I'm not familiar with this error. Perhaps it's similar to: https://github.com/rapidsai/crossfit/issues/84
cc: @VibhuJawa .

@pappagari Can you share the version of cuDF, CrossFit and method of Curator installation in your environment?

**Comment by pappagari** [comment]
I have two conda envs and somehow they ended up with two different packages. I think I uninstalled curator (through source) a couple of times and installed them again and in the process something changed. But it is working in one of the env.

For reference, here are the versions 
cuDF -- 24.8.3  -- working
cuDF -- 24.10.01 -- not working
Crossfit version 0.0.5 is same in both envs.
